### ISSUE TITLE
Missions not loading

### ISSUE THREAD

**Issue by wkzdylan** [ImagicTheCat/vRP-basic-mission#12]
Hey man, Great work on everything but the missions file refuses to load throwing errors i even tried it with your files with out any of my modifications

**Comment by ImagicTheCat** [comment]
Should be fixed, be more precise when you submit issues.

**Comment by wkzdylan** [comment]
Sorry man i was on my phone and didnt have the specific errors ill try your
fix if not ill upload the citizen fx log to pastebin for ya


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
